{% set name = "meamfit" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/AndyDuff123/meamfit/-/archive/4f66fd6bd6dea1066336e7e10ad7c1db132511b9/meamfit-4f66fd6bd6dea1066336e7e10ad7c1db132511b9.tar.gz
  sha256: 7362bf145fd9de0f7842c80887e7630cbe6928c8bf3e45fe5ff6f18e0d8e507f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - make
  host:
    - {{ mpi }}
    - libblas
    - liblapack
  run:

test:
  commands:
    - MEAMfit.x --help

about:
  home: https://gitlab.com/AndyDuff123/meamfit
  summary: 'A Fortran code to fit reference-free modified embedded atom method (RF-MEAM) interatomic potentials to density functional theory (DFT) data (VASP or CASTEP).'
  description: |
    Open-source MEAMfit2 code for fitting RF-MEAM (or EAM) potentials to VASP
    or CASTEP output data, to generate potentials that can be run using LAMMPS.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://gitlab.com/AndyDuff123/meamfit
  dev_url: https://gitlab.com/AndyDuff123/meamfit

extra:
  recipe-maintainers:
    - jan-janssen
